marks=[]
f1=int(input("Enter marks 1: "))
f2=int(input("Enter marks 2: "))
f3=int(input("Enter marks 3: "))
f4=int(input("Enter marks 4: "))
f5=int(input("Enter marks 5: "))
f6=int(input("Enter marks 6: "))
marks.append(f1)
marks.append(f2)
marks.append(f3)   
marks.append(f4)
marks.append(f5)
marks.append(f6)
marks.sort()
print(marks)